### ISSUE TITLE
http.post returns "getaddrinfo ENOTFOUND" error 

### ISSUE THREAD

**Issue by onkarkhokhar** [themakunga/transbank-sdk-node#4]
Hey Nicolas,

I am trying to use your package to implement transbank for nodejs,
I am getting this error when I am running your package in RunKit or locally, I have tried few things to fix it but they didn't work. Any idea what I can do to fix this
![image](https://user-images.githubusercontent.com/61167212/100265780-bf4dbf80-2f1e-11eb-99f8-3cea5599c07d.png)

This is the code I wrote to call create function
var transbankSdkNode = require("transbank-sdk-node")
var transaction = new transbankSdkNode.Transaction(
"test")
transaction.create()

**Comment by onkarkhokhar** [comment]
Removing https:// worked from url worked
![image](https://user-images.githubusercontent.com/61167212/100268456-15246680-2f23-11eb-9805-4fd82152d1ba.png)

**Comment by themakunga** [comment]
Thanks for your issue and PRs!
